### ISSUE TITLE
Corners Artifacts in Folders View in Gnome 42

### ISSUE THREAD

**Issue by theodormoroianu** [aunetx/blur-my-shell#200]
The folder icons in the Gnome Shell have grey artifacts around the corners:
![image](https://user-images.githubusercontent.com/8684801/158588675-2768cc60-0ff9-4a72-8af4-cdb6eff1b52d.png)

Without the extension no artifacts ar visible (probably because they have the same color as the background):
![image](https://user-images.githubusercontent.com/8684801/158588800-d315939c-123a-496a-9a92-33f1fed113a7.png)

Blur-my-shell version: `28`
Gnome version: `42.beta`
OS: `Fedora 36 Workstation Edition Prerelease`

**Comment by retrixe** [comment]
This occurs to me on Fedora 36 Prerelease as well. Editing `stylesheet.css` by commenting
```css
.blurred-overview .app-folder {
    background-color: rgba(0, 0, 0, 0.12);
}
```
out fixes this issue, like so:
```css
/* .blurred-overview .app-folder {
    background-color: rgba(0, 0, 0, 0.12);
} */
```

![image](https://user-images.githubusercontent.com/6884828/158677142-29e4ad9b-d6a5-4648-a94f-33f545aaac36.png)
