### ISSUE TITLE
Blur does not apply properly on Alacritty windows

### ISSUE THREAD

**Issue by Beast-Viper** [aunetx/blur-my-shell#622]
As the title says Blur My Shell does not blur properly on Alacritty windows. The only effect it has is to lighten up the background but no blur. Here are some samples:
![Screenshot from 2024-07-11 20-15-40](https://github.com/aunetx/blur-my-shell/assets/95138842/e9d21293-c7ac-4a2e-9bfc-e846e0ee20dd)
Blur disabled

![Screenshot from 2024-07-11 20-16-27](https://github.com/aunetx/blur-my-shell/assets/95138842/f52cc3d7-ecf8-4e42-85d2-923cec02cfb0)
Blur enabled

![Screenshot from 2024-07-11 20-18-06](https://github.com/aunetx/blur-my-shell/assets/95138842/615b4faa-3f27-4a18-b95a-9b902c725bd4)
Both windows have blur enabled. Image for comparison.

![image](https://github.com/aunetx/blur-my-shell/assets/95138842/af021e48-39a6-46f3-9259-5de192113b2c)
My system specs

**Comment by alosarjos** [comment]
Working fine here

![Captura desde 2024-07-21 19-12-04](https://github.com/user-attachments/assets/6f4d33e3-887c-4853-af8a-6f24ce94d71a)

**Comment by Beast-Viper** [comment]
> Working fine here
> 
> ![Captura desde 2024-07-21 19-12-04](https://private-user-images.githubusercontent.com/29999427/350784991-6f4d33e3-887c-4853-af8a-6f24ce94d71a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1ODIzMzQsIm5iZiI6MTcyMTU4MjAzNCwicGF0aCI6Ii8yOTk5OTQyNy8zNTA3ODQ5OTEtNmY0ZDMzZTMtODg3Yy00ODUzLWFmOGEtNmYyNGNlOTRkNzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDE3MTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYjBhYWJiZTc2YzRlNjBhNTUxMmQzYTdjNmFiNTJhNzFjY2UwNmEyNzAwOTViZWI2ZWYxYzAxZmRjZjJlYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nPdvZ9QKZaPAzXa5ZJoB_CjK2dsUZg2SnwWSE08sIJA)

Specs and software version?

**Comment by alosarjos** [comment]
Arch Linux with Gnome 46.3.1
Alacritty 0.13.2 (bb8ea18e)
BlurMyShell 62

Alacritty Config:

```toml
import = [
  "~/.config/alacritty/tokyonight_moon.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12.5

[window]
dimensions = { columns = 200, lines = 50 }
decorations_theme_variant = "Dark"
dynamic_title = false
opacity = 0.9

[keyboard]
bindings = [
  { key = "Q", mods = "Control", action = "Quit" },
]
```
